engines:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR1,PSR2"
      ignore_warnings: true
      encoding: utf-8
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,controversial,design,naming"
ratings:
  paths:
  - "**.php"
